#!/usr/bin/env python3
"""Convert Natural Earth 110m country polygons → src/coastline_data.h.

Output schema (PROGMEM int16 arrays):

    static const int16_t COAST_VERTS[] PROGMEM = { lat0*100, lng0*100, lat1*100, lng1*100, ... };
    static const uint16_t COAST_RING_OFFSETS[] PROGMEM = { 0, n0, n0+n1, ... };
    static const uint16_t COAST_RING_COUNT = N;

Each ring is a single closed polygon (outer ring of a country, plus any holes
or multipolygon parts as separate rings — we don't distinguish, since we only
draw outlines, not fills).

`lat*100` and `lng*100` give 0.01° precision (~1.1km at the equator). Good
enough for a 60-100px Earth disc.

Usage:
    cd SpaceTracker
    python3 tools/build_coastline.py
"""
import json
import os
import sys
import urllib.request

GEOJSON_URL = (
    "https://raw.githubusercontent.com/nvkelso/"
    "natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson"
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(ROOT, "src", "coastline_data.h")


def download_or_cache():
    cache = "/tmp/ne_110m_admin_0_countries.geojson"
    if os.path.exists(cache):
        with open(cache) as f:
            return json.load(f)
    print(f"downloading {GEOJSON_URL}…")
    req = urllib.request.Request(GEOJSON_URL, headers={"User-Agent": "spacetracker-build"})
    with urllib.request.urlopen(req, timeout=20) as r:
        data = r.read()
    with open(cache, "wb") as f:
        f.write(data)
    return json.loads(data)


def collect_rings(features):
    """Yield each polygon ring as a list of (lat, lng) tuples."""
    for feat in features:
        geom = feat.get("geometry") or {}
        gtype = geom.get("type")
        coords = geom.get("coordinates") or []
        if gtype == "Polygon":
            polygons = [coords]
        elif gtype == "MultiPolygon":
            polygons = coords
        else:
            continue
        for poly in polygons:
            for ring in poly:
                yield [(lat, lng) for (lng, lat) in ring]


def main():
    geojson = download_or_cache()
    rings = list(collect_rings(geojson["features"]))

    verts = []
    offsets = [0]
    for ring in rings:
        for (lat, lng) in ring:
            verts.append(int(round(lat * 100.0)))
            verts.append(int(round(lng * 100.0)))
        offsets.append(len(verts) // 2)  # offset is in vertex (pair) count

    print(f"  rings:    {len(rings)}")
    print(f"  vertices: {len(verts) // 2}")
    print(f"  bytes:    {len(verts) * 2 + len(offsets) * 2}")

    with open(OUT_PATH, "w") as f:
        f.write("// Generated by tools/build_coastline.py — do not edit by hand.\n")
        f.write("// Source: Natural Earth 110m admin_0 countries.\n")
        f.write("// Layout: int16 lat*100, lng*100 pairs; ring offsets in pair counts.\n")
        f.write("#pragma once\n#include <stdint.h>\n#include <pgmspace.h>\n\n")

        f.write(f"constexpr uint16_t COAST_RING_COUNT = {len(rings)};\n")
        f.write(f"constexpr uint32_t COAST_VERT_COUNT = {len(verts) // 2};\n\n")

        f.write("static const int16_t COAST_VERTS[] PROGMEM = {\n")
        for i in range(0, len(verts), 16):
            chunk = verts[i:i + 16]
            f.write("    " + ",".join(f"{v}" for v in chunk) + ",\n")
        f.write("};\n\n")

        f.write("static const uint16_t COAST_RING_OFFSETS[] PROGMEM = {\n")
        for i in range(0, len(offsets), 16):
            chunk = offsets[i:i + 16]
            f.write("    " + ",".join(f"{v}" for v in chunk) + ",\n")
        f.write("};\n")

    print(f"  wrote {OUT_PATH}")


if __name__ == "__main__":
    sys.exit(main())
